"""empty message

Revision ID: 48cd6e64ca0d
Revises: 
Create Date: 2019-12-04 14:26:13.315683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cd6e64ca0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('dates', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'dates')
    # ### end Alembic commands ###
