"""empty message

Revision ID: 6322ff4da6a1
Revises: 48cd6e64ca0d
Create Date: 2019-12-04 18:44:41.201026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6322ff4da6a1'
down_revision = '48cd6e64ca0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('creator', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'creator')
    # ### end Alembic commands ###
