"""empty message

Revision ID: cbe58d152f30
Revises: 6322ff4da6a1
Create Date: 2019-12-04 18:57:33.587020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe58d152f30'
down_revision = '6322ff4da6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('creatorId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'creatorId')
    # ### end Alembic commands ###
